language: node_js
node_js:
- node
- 8
after_success:
- npm run coverage
- npm run build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key:
    secure: XKQSdTq740HCigD7HqyEdGcQn2FYPW8pkH9EYKWv7ZRpStI4O5svdG7lSG/vH5YwsDlIwbg+PmNIwA4TdWj/7gzxA9f5Dn45z0WXuipiFcw+hbGwMhXanscnmH6FiwKSw12Zxde/Cug+Sza7ZM4X5OEVZjLQiwpLUMdfyNuFn1QtHzvN0xN9J5GOFlWWBdXpcdCBe2QRx7CGacLwcFtWjRUQiYqtcnGYJfqaoAojqjJ/9XH0ilodnTSXDqVIN88ETGZCnDxZZhT2MT/WuVRKVRuSHvUwwtntNp995X45lLXJqUON8zAu1z+Ut7NXEW7M1UISQvVq8kLzEIHSJL0IbUffbCumrSz7aFSrKOz78zZSNoVhNSF8siQEYbMUYXoFtEEoXK0IvLK4r0hIqiXUf1oxqh6yOKYXcJ1R/53hCNl5smwWR032aDa222JnMiFJdHsu1DwLlxQr2RJX/0bmhNVgJjwswX43PWOMgTPfoeREno0SNIRIkfEy4aI11URzo5W2zpXhzt5KHPuloITG6CwYWR9l7+XriJNx4yHzIO7szXXROsoGqsuiRV09KABG7CD0kZ3mizqS/kPxeWcHvTmlpCtoPC04EaBVXqJXD1QCDrQKybnQp0YBCw7AeLQp5dp7gxRtS2oy8F1J/DrjNFJequjbVF3GnvaCRi1omRU=
  skip_cleanup: true
  on:
    repo: up9cloud/graphql-tools-type-uint
    branch: master
