language: node_js
node_js:
- node
- 10
- 8
after_success:
- npm run coverage
- npm run build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key:
    secure: GhYTh8zPSiiKU/nphfbD9ZB5906OD5yaEPfJz17pmXjzrBzlpcmAmOOl3CsPwbwh3UP1hJh11RMJrC3Q0+7fA0IkKWUPceVktfmlS94mWvJR0yGZnxd7n5u7teWJkxOkCPpxA9B/QWHaqNCjm4uPsmeW190x6H6WvT0x6mPIQBoRTclkBqF64MOMg/wmtvAvzqNpl7g6GY3/qsU6TLFuzkMop2+phI4CF9HuWW4Fm/lQ88G8AMXPKhhLJQJf6rtlrmh2B2EEMfanqOVDyrZoblffrryeXN2PIPhEhGXMEIMSQunxfny7aVdj9FmUAaLMIR1FSPDLHsTYDedT1viucJ9gek61vdW4bI00+w9hga4DIdV1NvjZ0FP/VyQOdzKZ979ncbZyaf8dax3ynl3FVsuiS0Geoqmc7+TS5wxEAdkv2ShoL9yrhe8cDoNMTosMMhhViA5V+/N9Jv4DsJRxOkF7M6vKTMNnqA9YKJmqKehtgHRBAQqTyYrILV6oqQfCdYthlhrdTLOKTCmrVxKHd5hcpqYagYOYllvM03F12j47G9vdtZ7/gRuWh0pV1Sgrvsc3L4o0KjN3U2YpIanDvf2ldVQp9Tonn//3k/KUYl7XzuACKORUq3EjZZCF5ppnGhBR0uCAKJuEbAiT8SJ3bENMkeGFhs/5icnrS8UP1mk=
  on:
    tags: true
    repo: up9cloud/graphql-tools-type-uint
    branch: master
  skip_cleanup: true
